server:
  port: 8080

spring:
  config:
    import: optional:configserver:http://localhost:9090

  datasource:
    url: jdbc:postgresql://localhost:5432/akka_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: NON_NULL

  security:
    enabled: false

logging:
  level:
    com.example: DEBUG
    org.springframework.web: DEBUG
